import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilRootWrapper from '../../wrappers/RecoilRootWrapper'
import Header from '../../components/layout/header'
import Footer from '../../components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(
    {children,}: 
    {children: React.ReactNode}) {

    return (
        <html lang="ko">
            <body
                className={``}
            >
                <Header />
                <div>
                    <RecoilRootWrapper>
                        {children}
                    </RecoilRootWrapper>
                </div>
                <Footer />
                
            </body>
        </html>
    )
}